/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 21/09/2017 14:52:32
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            25000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_PLLCLKFreq_Value                     180000000
#define MX_SYSCLKFreq_VALUE                     180000000
#define MX_HCLKFreq_Value                       180000000
#define MX_FCLKCortexFreq_Value                 180000000
#define MX_CortexFreq_Value                     180000000
#define MX_AHBFreq_Value                        180000000
#define MX_APB1Freq_Value                       45000000
#define MX_APB2Freq_Value                       90000000
#define MX_APB1TimFreq_Value                    90000000
#define MX_APB2TimFreq_Value                    180000000
#define MX_48MHZClocksFreq_Value                90000000
#define MX_EthernetFreq_Value                   180000000
#define MX_LCDTFTFreq_Value                     24500000
#define MX_I2SClocksFreq_Value                  192000000
#define MX_SAI_AClocksFreq_Value                24500000
#define MX_SAI_BClocksFreq_Value                24500000
#define MX_RTCFreq_Value                        32000
#define MX_WatchDogFreq_Value                   32000
#define MX_MCO1PinFreq_Value                    16000000
#define MX_MCO2PinFreq_Value                    180000000

/*-------------------------------- ADC1       --------------------------------*/

#define MX_ADC1                                 1

/* GPIO Configuration */

/* Pin PA5 */
#define MX_ADCx_IN5_Pin                         PA5
#define MX_ADCx_IN5_GPIOx                       GPIOA
#define MX_ADCx_IN5_GPIO_PuPd                   GPIO_NOPULL
#define MX_ADCx_IN5_GPIO_Pin                    GPIO_PIN_5
#define MX_ADCx_IN5_GPIO_Mode                   GPIO_MODE_ANALOG

/* Pin PA6 */
#define MX_ADCx_IN6_Pin                         PA6
#define MX_ADCx_IN6_GPIOx                       GPIOA
#define MX_ADCx_IN6_GPIO_PuPd                   GPIO_NOPULL
#define MX_ADCx_IN6_GPIO_Pin                    GPIO_PIN_6
#define MX_ADCx_IN6_GPIO_Mode                   GPIO_MODE_ANALOG

/*-------------------------------- CAN1       --------------------------------*/

#define MX_CAN1                                 1

/* GPIO Configuration */

/* Pin PA11 */
#define MX_CAN1_RX_GPIO_Speed                   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_CAN1_RX_Pin                          PA11
#define MX_CAN1_RX_GPIOx                        GPIOA
#define MX_CAN1_RX_GPIO_PuPd                    GPIO_NOPULL
#define MX_CAN1_RX_GPIO_Pin                     GPIO_PIN_11
#define MX_CAN1_RX_GPIO_AF                      GPIO_AF9_CAN1
#define MX_CAN1_RX_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PA12 */
#define MX_CAN1_TX_GPIO_Speed                   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_CAN1_TX_Pin                          PA12
#define MX_CAN1_TX_GPIOx                        GPIOA
#define MX_CAN1_TX_GPIO_PuPd                    GPIO_NOPULL
#define MX_CAN1_TX_GPIO_Pin                     GPIO_PIN_12
#define MX_CAN1_TX_GPIO_AF                      GPIO_AF9_CAN1
#define MX_CAN1_TX_GPIO_Mode                    GPIO_MODE_AF_PP

/*-------------------------------- CAN2       --------------------------------*/

#define MX_CAN2                                 1

/* GPIO Configuration */

/* Pin PB12 */
#define MX_CAN2_RX_GPIO_Speed                   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_CAN2_RX_Pin                          PB12
#define MX_CAN2_RX_GPIOx                        GPIOB
#define MX_CAN2_RX_GPIO_PuPd                    GPIO_NOPULL
#define MX_CAN2_RX_GPIO_Pin                     GPIO_PIN_12
#define MX_CAN2_RX_GPIO_AF                      GPIO_AF9_CAN2
#define MX_CAN2_RX_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PB13 */
#define MX_CAN2_TX_GPIO_Speed                   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_CAN2_TX_Pin                          PB13
#define MX_CAN2_TX_GPIOx                        GPIOB
#define MX_CAN2_TX_GPIO_PuPd                    GPIO_NOPULL
#define MX_CAN2_TX_GPIO_Pin                     GPIO_PIN_13
#define MX_CAN2_TX_GPIO_AF                      GPIO_AF9_CAN2
#define MX_CAN2_TX_GPIO_Mode                    GPIO_MODE_AF_PP

/*-------------------------------- DAC        --------------------------------*/

#define MX_DAC                                  1

/* GPIO Configuration */

/* Pin PA4 */
#define MX_COMP_DAC1_group_Pin                  PA4
#define MX_COMP_DAC1_group_GPIOx                GPIOA
#define MX_COMP_DAC1_group_GPIO_PuPd            GPIO_NOPULL
#define MX_COMP_DAC1_group_GPIO_Pin             GPIO_PIN_4
#define MX_COMP_DAC1_group_GPIO_Mode            GPIO_MODE_ANALOG

/*-------------------------------- I2C1       --------------------------------*/

#define MX_I2C1                                 1

/* GPIO Configuration */

/* Pin PB6 */
#define MX_I2C1_SCL_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C1_SCL_Pin                         PB6
#define MX_I2C1_SCL_GPIOx                       GPIOB
#define MX_I2C1_SCL_GPIO_PuPdOD                 GPIO_PULLUP
#define MX_I2C1_SCL_GPIO_Pin                    GPIO_PIN_6
#define MX_I2C1_SCL_GPIO_AF                     GPIO_AF4_I2C1
#define MX_I2C1_SCL_GPIO_Mode                   GPIO_MODE_AF_OD

/* Pin PB7 */
#define MX_I2C1_SDA_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C1_SDA_Pin                         PB7
#define MX_I2C1_SDA_GPIOx                       GPIOB
#define MX_I2C1_SDA_GPIO_PuPdOD                 GPIO_PULLUP
#define MX_I2C1_SDA_GPIO_Pin                    GPIO_PIN_7
#define MX_I2C1_SDA_GPIO_AF                     GPIO_AF4_I2C1
#define MX_I2C1_SDA_GPIO_Mode                   GPIO_MODE_AF_OD

/*-------------------------------- I2C2       --------------------------------*/

#define MX_I2C2                                 1

/* GPIO Configuration */

/* Pin PF0 */
#define MX_I2C2_SDA_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C2_SDA_Pin                         PF0
#define MX_I2C2_SDA_GPIOx                       GPIOF
#define MX_I2C2_SDA_GPIO_PuPdOD                 GPIO_PULLUP
#define MX_I2C2_SDA_GPIO_Pin                    GPIO_PIN_0
#define MX_I2C2_SDA_GPIO_AF                     GPIO_AF4_I2C2
#define MX_I2C2_SDA_GPIO_Mode                   GPIO_MODE_AF_OD

/* Pin PF1 */
#define MX_I2C2_SCL_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C2_SCL_Pin                         PF1
#define MX_I2C2_SCL_GPIOx                       GPIOF
#define MX_I2C2_SCL_GPIO_PuPdOD                 GPIO_PULLUP
#define MX_I2C2_SCL_GPIO_Pin                    GPIO_PIN_1
#define MX_I2C2_SCL_GPIO_AF                     GPIO_AF4_I2C2
#define MX_I2C2_SCL_GPIO_Mode                   GPIO_MODE_AF_OD

/*-------------------------------- SPI5       --------------------------------*/

#define MX_SPI5                                 1

/* GPIO Configuration */

/* Pin PH6 */
#define MX_SPI5_SCK_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI5_SCK_Pin                         PH6
#define MX_SPI5_SCK_GPIOx                       GPIOH
#define MX_SPI5_SCK_GPIO_PuPd                   GPIO_NOPULL
#define MX_SPI5_SCK_GPIO_Pin                    GPIO_PIN_6
#define MX_SPI5_SCK_GPIO_AF                     GPIO_AF5_SPI5
#define MX_SPI5_SCK_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PF11 */
#define MX_SPI5_MOSI_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI5_MOSI_Pin                        PF11
#define MX_SPI5_MOSI_GPIOx                      GPIOF
#define MX_SPI5_MOSI_GPIO_PuPd                  GPIO_NOPULL
#define MX_SPI5_MOSI_GPIO_Pin                   GPIO_PIN_11
#define MX_SPI5_MOSI_GPIO_AF                    GPIO_AF5_SPI5
#define MX_SPI5_MOSI_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PH7 */
#define MX_SPI5_MISO_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI5_MISO_Pin                        PH7
#define MX_SPI5_MISO_GPIOx                      GPIOH
#define MX_SPI5_MISO_GPIO_PuPd                  GPIO_NOPULL
#define MX_SPI5_MISO_GPIO_Pin                   GPIO_PIN_7
#define MX_SPI5_MISO_GPIO_AF                    GPIO_AF5_SPI5
#define MX_SPI5_MISO_GPIO_Mode                  GPIO_MODE_AF_PP

/*-------------------------------- SPI6       --------------------------------*/

#define MX_SPI6                                 1

/* GPIO Configuration */

/* Pin PG12 */
#define MX_SPI6_MISO_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI6_MISO_Pin                        PG12
#define MX_SPI6_MISO_GPIOx                      GPIOG
#define MX_SPI6_MISO_GPIO_PuPd                  GPIO_NOPULL
#define MX_SPI6_MISO_GPIO_Pin                   GPIO_PIN_12
#define MX_SPI6_MISO_GPIO_AF                    GPIO_AF5_SPI6
#define MX_SPI6_MISO_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PG14 */
#define MX_SPI6_MOSI_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI6_MOSI_Pin                        PG14
#define MX_SPI6_MOSI_GPIOx                      GPIOG
#define MX_SPI6_MOSI_GPIO_PuPd                  GPIO_NOPULL
#define MX_SPI6_MOSI_GPIO_Pin                   GPIO_PIN_14
#define MX_SPI6_MOSI_GPIO_AF                    GPIO_AF5_SPI6
#define MX_SPI6_MOSI_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PG13 */
#define MX_SPI6_SCK_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI6_SCK_Pin                         PG13
#define MX_SPI6_SCK_GPIOx                       GPIOG
#define MX_SPI6_SCK_GPIO_PuPd                   GPIO_NOPULL
#define MX_SPI6_SCK_GPIO_Pin                    GPIO_PIN_13
#define MX_SPI6_SCK_GPIO_AF                     GPIO_AF5_SPI6
#define MX_SPI6_SCK_GPIO_Mode                   GPIO_MODE_AF_PP

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/* Pin PA13 */
#define MX_SYS_JTMS-SWDIO_Pin                   PA13

/* Pin PA14 */
#define MX_SYS_JTCK-SWCLK_Pin                   PA14

/*-------------------------------- TIM1       --------------------------------*/

#define MX_TIM1                                 1

/* GPIO Configuration */

/* Pin PE9 */
#define MX_S_TIM1_CH1_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM1_CH1_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM1_CH1_Pin                       PE9
#define MX_S_TIM1_CH1_GPIOx                     GPIOE
#define MX_S_TIM1_CH1_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM1_CH1_GPIO_Pin                  GPIO_PIN_9
#define MX_S_TIM1_CH1_GPIO_AF                   GPIO_AF1_TIM1

/* Pin PE11 */
#define MX_S_TIM1_CH2_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM1_CH2_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM1_CH2_Pin                       PE11
#define MX_S_TIM1_CH2_GPIOx                     GPIOE
#define MX_S_TIM1_CH2_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM1_CH2_GPIO_Pin                  GPIO_PIN_11
#define MX_S_TIM1_CH2_GPIO_AF                   GPIO_AF1_TIM1

/* Pin PE10 */
#define MX_TIM1_CH2N_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_TIM1_CH2N_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_TIM1_CH2N_Pin                        PE10
#define MX_TIM1_CH2N_GPIOx                      GPIOE
#define MX_TIM1_CH2N_GPIO_PuPd                  GPIO_NOPULL
#define MX_TIM1_CH2N_GPIO_Pin                   GPIO_PIN_10
#define MX_TIM1_CH2N_GPIO_AF                    GPIO_AF1_TIM1

/* Pin PE13 */
#define MX_S_TIM1_CH3_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM1_CH3_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM1_CH3_Pin                       PE13
#define MX_S_TIM1_CH3_GPIOx                     GPIOE
#define MX_S_TIM1_CH3_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM1_CH3_GPIO_Pin                  GPIO_PIN_13
#define MX_S_TIM1_CH3_GPIO_AF                   GPIO_AF1_TIM1

/* Pin PE12 */
#define MX_TIM1_CH3N_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_TIM1_CH3N_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_TIM1_CH3N_Pin                        PE12
#define MX_TIM1_CH3N_GPIOx                      GPIOE
#define MX_TIM1_CH3N_GPIO_PuPd                  GPIO_NOPULL
#define MX_TIM1_CH3N_GPIO_Pin                   GPIO_PIN_12
#define MX_TIM1_CH3N_GPIO_AF                    GPIO_AF1_TIM1

/* Pin PE8 */
#define MX_TIM1_CH1N_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_TIM1_CH1N_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_TIM1_CH1N_Pin                        PE8
#define MX_TIM1_CH1N_GPIOx                      GPIOE
#define MX_TIM1_CH1N_GPIO_PuPd                  GPIO_NOPULL
#define MX_TIM1_CH1N_GPIO_Pin                   GPIO_PIN_8
#define MX_TIM1_CH1N_GPIO_AF                    GPIO_AF1_TIM1

/*-------------------------------- TIM2       --------------------------------*/

#define MX_TIM2                                 1

/* GPIO Configuration */

/* Pin PA1 */
#define MX_S_TIM2_CH2_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM2_CH2_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM2_CH2_Pin                       PA1
#define MX_S_TIM2_CH2_GPIOx                     GPIOA
#define MX_S_TIM2_CH2_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM2_CH2_GPIO_Pin                  GPIO_PIN_1
#define MX_S_TIM2_CH2_GPIO_AF                   GPIO_AF1_TIM2

/* Pin PA2 */
#define MX_S_TIM2_CH3_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM2_CH3_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM2_CH3_Pin                       PA2
#define MX_S_TIM2_CH3_GPIOx                     GPIOA
#define MX_S_TIM2_CH3_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM2_CH3_GPIO_Pin                  GPIO_PIN_2
#define MX_S_TIM2_CH3_GPIO_AF                   GPIO_AF1_TIM2

/* Pin PA0/WKUP */
#define MX_S_TIM2_CH1_ETR_GPIO_ModeDefaultPP    GPIO_MODE_AF_PP
#define MX_S_TIM2_CH1_ETR_GPIO_Speed            GPIO_SPEED_FREQ_LOW
#define MX_S_TIM2_CH1_ETR_Pin                   PA0_WKUP
#define MX_S_TIM2_CH1_ETR_GPIOx                 GPIOA
#define MX_S_TIM2_CH1_ETR_GPIO_PuPd             GPIO_NOPULL
#define MX_S_TIM2_CH1_ETR_GPIO_Pin              GPIO_PIN_0
#define MX_S_TIM2_CH1_ETR_GPIO_AF               GPIO_AF1_TIM2

/*-------------------------------- TIM3       --------------------------------*/

#define MX_TIM3                                 1

/* GPIO Configuration */

/* Pin PC8 */
#define MX_S_TIM3_CH3_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM3_CH3_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM3_CH3_Pin                       PC8
#define MX_S_TIM3_CH3_GPIOx                     GPIOC
#define MX_S_TIM3_CH3_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM3_CH3_GPIO_Pin                  GPIO_PIN_8
#define MX_S_TIM3_CH3_GPIO_AF                   GPIO_AF2_TIM3

/* Pin PC6 */
#define MX_S_TIM3_CH1_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM3_CH1_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM3_CH1_Pin                       PC6
#define MX_S_TIM3_CH1_GPIOx                     GPIOC
#define MX_S_TIM3_CH1_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM3_CH1_GPIO_Pin                  GPIO_PIN_6
#define MX_S_TIM3_CH1_GPIO_AF                   GPIO_AF2_TIM3

/* Pin PC7 */
#define MX_S_TIM3_CH2_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM3_CH2_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM3_CH2_Pin                       PC7
#define MX_S_TIM3_CH2_GPIOx                     GPIOC
#define MX_S_TIM3_CH2_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM3_CH2_GPIO_Pin                  GPIO_PIN_7
#define MX_S_TIM3_CH2_GPIO_AF                   GPIO_AF2_TIM3

/*-------------------------------- TIM4       --------------------------------*/

#define MX_TIM4                                 1

/* GPIO Configuration */

/* Pin PD12 */
#define MX_S_TIM4_CH1_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM4_CH1_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM4_CH1_Pin                       PD12
#define MX_S_TIM4_CH1_GPIOx                     GPIOD
#define MX_S_TIM4_CH1_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM4_CH1_GPIO_Pin                  GPIO_PIN_12
#define MX_S_TIM4_CH1_GPIO_AF                   GPIO_AF2_TIM4

/* Pin PD13 */
#define MX_S_TIM4_CH2_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM4_CH2_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM4_CH2_Pin                       PD13
#define MX_S_TIM4_CH2_GPIOx                     GPIOD
#define MX_S_TIM4_CH2_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM4_CH2_GPIO_Pin                  GPIO_PIN_13
#define MX_S_TIM4_CH2_GPIO_AF                   GPIO_AF2_TIM4

/* Pin PD14 */
#define MX_S_TIM4_CH3_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM4_CH3_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM4_CH3_Pin                       PD14
#define MX_S_TIM4_CH3_GPIOx                     GPIOD
#define MX_S_TIM4_CH3_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM4_CH3_GPIO_Pin                  GPIO_PIN_14
#define MX_S_TIM4_CH3_GPIO_AF                   GPIO_AF2_TIM4

/*-------------------------------- TIM5       --------------------------------*/

#define MX_TIM5                                 1

/* GPIO Configuration */

/* Pin PH12 */
#define MX_S_TIM5_CH3_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM5_CH3_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM5_CH3_Pin                       PH12
#define MX_S_TIM5_CH3_GPIOx                     GPIOH
#define MX_S_TIM5_CH3_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM5_CH3_GPIO_Pin                  GPIO_PIN_12
#define MX_S_TIM5_CH3_GPIO_AF                   GPIO_AF2_TIM5

/* Pin PI0 */
#define MX_S_TIM5_CH4_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM5_CH4_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM5_CH4_Pin                       PI0
#define MX_S_TIM5_CH4_GPIOx                     GPIOI
#define MX_S_TIM5_CH4_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM5_CH4_GPIO_Pin                  GPIO_PIN_0
#define MX_S_TIM5_CH4_GPIO_AF                   GPIO_AF2_TIM5

/* Pin PH10 */
#define MX_S_TIM5_CH1_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM5_CH1_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM5_CH1_Pin                       PH10
#define MX_S_TIM5_CH1_GPIOx                     GPIOH
#define MX_S_TIM5_CH1_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM5_CH1_GPIO_Pin                  GPIO_PIN_10
#define MX_S_TIM5_CH1_GPIO_AF                   GPIO_AF2_TIM5

/* Pin PH11 */
#define MX_S_TIM5_CH2_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM5_CH2_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM5_CH2_Pin                       PH11
#define MX_S_TIM5_CH2_GPIOx                     GPIOH
#define MX_S_TIM5_CH2_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM5_CH2_GPIO_Pin                  GPIO_PIN_11
#define MX_S_TIM5_CH2_GPIO_AF                   GPIO_AF2_TIM5

/*-------------------------------- TIM8       --------------------------------*/

#define MX_TIM8                                 1

/* GPIO Configuration */

/* Pin PH13 */
#define MX_TIM8_CH1N_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_TIM8_CH1N_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_TIM8_CH1N_Pin                        PH13
#define MX_TIM8_CH1N_GPIOx                      GPIOH
#define MX_TIM8_CH1N_GPIO_PuPd                  GPIO_NOPULL
#define MX_TIM8_CH1N_GPIO_Pin                   GPIO_PIN_13
#define MX_TIM8_CH1N_GPIO_AF                    GPIO_AF3_TIM8

/* Pin PH14 */
#define MX_TIM8_CH2N_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_TIM8_CH2N_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_TIM8_CH2N_Pin                        PH14
#define MX_TIM8_CH2N_GPIOx                      GPIOH
#define MX_TIM8_CH2N_GPIO_PuPd                  GPIO_NOPULL
#define MX_TIM8_CH2N_GPIO_Pin                   GPIO_PIN_14
#define MX_TIM8_CH2N_GPIO_AF                    GPIO_AF3_TIM8

/* Pin PI2 */
#define MX_S_TIM8_CH4_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM8_CH4_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM8_CH4_Pin                       PI2
#define MX_S_TIM8_CH4_GPIOx                     GPIOI
#define MX_S_TIM8_CH4_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM8_CH4_GPIO_Pin                  GPIO_PIN_2
#define MX_S_TIM8_CH4_GPIO_AF                   GPIO_AF3_TIM8

/* Pin PH15 */
#define MX_TIM8_CH3N_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_TIM8_CH3N_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_TIM8_CH3N_Pin                        PH15
#define MX_TIM8_CH3N_GPIOx                      GPIOH
#define MX_TIM8_CH3N_GPIO_PuPd                  GPIO_NOPULL
#define MX_TIM8_CH3N_GPIO_Pin                   GPIO_PIN_15
#define MX_TIM8_CH3N_GPIO_AF                    GPIO_AF3_TIM8

/* Pin PI5 */
#define MX_S_TIM8_CH1_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM8_CH1_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM8_CH1_Pin                       PI5
#define MX_S_TIM8_CH1_GPIOx                     GPIOI
#define MX_S_TIM8_CH1_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM8_CH1_GPIO_Pin                  GPIO_PIN_5
#define MX_S_TIM8_CH1_GPIO_AF                   GPIO_AF3_TIM8

/* Pin PI6 */
#define MX_S_TIM8_CH2_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM8_CH2_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM8_CH2_Pin                       PI6
#define MX_S_TIM8_CH2_GPIOx                     GPIOI
#define MX_S_TIM8_CH2_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM8_CH2_GPIO_Pin                  GPIO_PIN_6
#define MX_S_TIM8_CH2_GPIO_AF                   GPIO_AF3_TIM8

/* Pin PI7 */
#define MX_S_TIM8_CH3_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM8_CH3_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM8_CH3_Pin                       PI7
#define MX_S_TIM8_CH3_GPIOx                     GPIOI
#define MX_S_TIM8_CH3_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM8_CH3_GPIO_Pin                  GPIO_PIN_7
#define MX_S_TIM8_CH3_GPIO_AF                   GPIO_AF3_TIM8

/*-------------------------------- TIM9       --------------------------------*/

#define MX_TIM9                                 1

/* GPIO Configuration */

/* Pin PE6 */
#define MX_S_TIM9_CH2_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM9_CH2_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM9_CH2_Pin                       PE6
#define MX_S_TIM9_CH2_GPIOx                     GPIOE
#define MX_S_TIM9_CH2_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM9_CH2_GPIO_Pin                  GPIO_PIN_6
#define MX_S_TIM9_CH2_GPIO_AF                   GPIO_AF3_TIM9

/* Pin PE5 */
#define MX_S_TIM9_CH1_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM9_CH1_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM9_CH1_Pin                       PE5
#define MX_S_TIM9_CH1_GPIOx                     GPIOE
#define MX_S_TIM9_CH1_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM9_CH1_GPIO_Pin                  GPIO_PIN_5
#define MX_S_TIM9_CH1_GPIO_AF                   GPIO_AF3_TIM9

/*-------------------------------- TIM10      --------------------------------*/

#define MX_TIM10                                1

/* GPIO Configuration */

/* Pin PF6 */
#define MX_S_TIM10_CH1_GPIO_ModeDefaultPP       GPIO_MODE_AF_PP
#define MX_S_TIM10_CH1_GPIO_Speed               GPIO_SPEED_FREQ_LOW
#define MX_S_TIM10_CH1_Pin                      PF6
#define MX_S_TIM10_CH1_GPIOx                    GPIOF
#define MX_S_TIM10_CH1_GPIO_PuPd                GPIO_NOPULL
#define MX_S_TIM10_CH1_GPIO_Pin                 GPIO_PIN_6
#define MX_S_TIM10_CH1_GPIO_AF                  GPIO_AF3_TIM10

/*-------------------------------- TIM11      --------------------------------*/

#define MX_TIM11                                1

/* GPIO Configuration */

/* Pin PF7 */
#define MX_S_TIM11_CH1_GPIO_ModeDefaultPP       GPIO_MODE_AF_PP
#define MX_S_TIM11_CH1_GPIO_Speed               GPIO_SPEED_FREQ_LOW
#define MX_S_TIM11_CH1_Pin                      PF7
#define MX_S_TIM11_CH1_GPIOx                    GPIOF
#define MX_S_TIM11_CH1_GPIO_PuPd                GPIO_NOPULL
#define MX_S_TIM11_CH1_GPIO_Pin                 GPIO_PIN_7
#define MX_S_TIM11_CH1_GPIO_AF                  GPIO_AF3_TIM11

/*-------------------------------- TIM12      --------------------------------*/

#define MX_TIM12                                1

/* GPIO Configuration */

/* Pin PB15 */
#define MX_S_TIM12_CH2_GPIO_ModeDefaultPP       GPIO_MODE_AF_PP
#define MX_S_TIM12_CH2_GPIO_Speed               GPIO_SPEED_FREQ_LOW
#define MX_S_TIM12_CH2_Pin                      PB15
#define MX_S_TIM12_CH2_GPIOx                    GPIOB
#define MX_S_TIM12_CH2_GPIO_PuPd                GPIO_NOPULL
#define MX_S_TIM12_CH2_GPIO_Pin                 GPIO_PIN_15
#define MX_S_TIM12_CH2_GPIO_AF                  GPIO_AF9_TIM12

/* Pin PB14 */
#define MX_S_TIM12_CH1_GPIO_ModeDefaultPP       GPIO_MODE_AF_PP
#define MX_S_TIM12_CH1_GPIO_Speed               GPIO_SPEED_FREQ_LOW
#define MX_S_TIM12_CH1_Pin                      PB14
#define MX_S_TIM12_CH1_GPIOx                    GPIOB
#define MX_S_TIM12_CH1_GPIO_PuPd                GPIO_NOPULL
#define MX_S_TIM12_CH1_GPIO_Pin                 GPIO_PIN_14
#define MX_S_TIM12_CH1_GPIO_AF                  GPIO_AF9_TIM12

/*-------------------------------- TIM13      --------------------------------*/

#define MX_TIM13                                1

/* GPIO Configuration */

/* Pin PF8 */
#define MX_S_TIM13_CH1_GPIO_ModeDefaultPP       GPIO_MODE_AF_PP
#define MX_S_TIM13_CH1_GPIO_Speed               GPIO_SPEED_FREQ_LOW
#define MX_S_TIM13_CH1_Pin                      PF8
#define MX_S_TIM13_CH1_GPIOx                    GPIOF
#define MX_S_TIM13_CH1_GPIO_PuPd                GPIO_NOPULL
#define MX_S_TIM13_CH1_GPIO_Pin                 GPIO_PIN_8
#define MX_S_TIM13_CH1_GPIO_AF                  GPIO_AF9_TIM13

/*-------------------------------- TIM14      --------------------------------*/

#define MX_TIM14                                1

/* GPIO Configuration */

/* Pin PF9 */
#define MX_S_TIM14_CH1_GPIO_ModeDefaultPP       GPIO_MODE_AF_PP
#define MX_S_TIM14_CH1_GPIO_Speed               GPIO_SPEED_FREQ_LOW
#define MX_S_TIM14_CH1_Pin                      PF9
#define MX_S_TIM14_CH1_GPIOx                    GPIOF
#define MX_S_TIM14_CH1_GPIO_PuPd                GPIO_NOPULL
#define MX_S_TIM14_CH1_GPIO_Pin                 GPIO_PIN_9
#define MX_S_TIM14_CH1_GPIO_AF                  GPIO_AF9_TIM14

/*-------------------------------- UART5      --------------------------------*/

#define MX_UART5                                1

#define MX_UART5_VM                             VM_ASYNC

/* GPIO Configuration */

/* Pin PD2 */
#define MX_UART5_RX_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_UART5_RX_Pin                         PD2
#define MX_UART5_RX_GPIOx                       GPIOD
#define MX_UART5_RX_GPIO_PuPd                   GPIO_NOPULL
#define MX_UART5_RX_GPIO_Pin                    GPIO_PIN_2
#define MX_UART5_RX_GPIO_AF                     GPIO_AF8_UART5
#define MX_UART5_RX_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PC12 */
#define MX_UART5_TX_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_UART5_TX_Pin                         PC12
#define MX_UART5_TX_GPIOx                       GPIOC
#define MX_UART5_TX_GPIO_PuPd                   GPIO_NOPULL
#define MX_UART5_TX_GPIO_Pin                    GPIO_PIN_12
#define MX_UART5_TX_GPIO_AF                     GPIO_AF8_UART5
#define MX_UART5_TX_GPIO_Mode                   GPIO_MODE_AF_PP

/*-------------------------------- USART1     --------------------------------*/

#define MX_USART1                               1

#define MX_USART1_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PA9 */
#define MX_USART1_TX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART1_TX_Pin                        PA9
#define MX_USART1_TX_GPIOx                      GPIOA
#define MX_USART1_TX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART1_TX_GPIO_Pin                   GPIO_PIN_9
#define MX_USART1_TX_GPIO_AF                    GPIO_AF7_USART1
#define MX_USART1_TX_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PA10 */
#define MX_USART1_RX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART1_RX_Pin                        PA10
#define MX_USART1_RX_GPIOx                      GPIOA
#define MX_USART1_RX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART1_RX_GPIO_Pin                   GPIO_PIN_10
#define MX_USART1_RX_GPIO_AF                    GPIO_AF7_USART1
#define MX_USART1_RX_GPIO_Mode                  GPIO_MODE_AF_PP

/*-------------------------------- USART3     --------------------------------*/

#define MX_USART3                               1

#define MX_USART3_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PC10 */
#define MX_USART3_TX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART3_TX_Pin                        PC10
#define MX_USART3_TX_GPIOx                      GPIOC
#define MX_USART3_TX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART3_TX_GPIO_Pin                   GPIO_PIN_10
#define MX_USART3_TX_GPIO_AF                    GPIO_AF7_USART3
#define MX_USART3_TX_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PC11 */
#define MX_USART3_RX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART3_RX_Pin                        PC11
#define MX_USART3_RX_GPIOx                      GPIOC
#define MX_USART3_RX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART3_RX_GPIO_Pin                   GPIO_PIN_11
#define MX_USART3_RX_GPIO_AF                    GPIO_AF7_USART3
#define MX_USART3_RX_GPIO_Mode                  GPIO_MODE_AF_PP

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PB3 */
#define MX_PB3_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB3_Pin                              PB3
#define MX_PB3_GPIOx                            GPIOB
#define MX_PB3_PinState                         GPIO_PIN_RESET
#define MX_PB3_GPIO_PuPd                        GPIO_NOPULL
#define MX_PB3_GPIO_Pin                         GPIO_PIN_3
#define MX_PB3_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PB5 */
#define MX_PB5_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB5_Pin                              PB5
#define MX_PB5_GPIOx                            GPIOB
#define MX_PB5_PinState                         GPIO_PIN_RESET
#define MX_PB5_GPIO_PuPd                        GPIO_NOPULL
#define MX_PB5_GPIO_Pin                         GPIO_PIN_5
#define MX_PB5_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PB4 */
#define MX_PB4_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB4_Pin                              PB4
#define MX_PB4_GPIOx                            GPIOB
#define MX_PB4_PinState                         GPIO_PIN_RESET
#define MX_PB4_GPIO_PuPd                        GPIO_NOPULL
#define MX_PB4_GPIO_Pin                         GPIO_PIN_4
#define MX_PB4_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PB9 */
#define MX_PB9_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB9_Pin                              PB9
#define MX_PB9_GPIOx                            GPIOB
#define MX_PB9_PinState                         GPIO_PIN_RESET
#define MX_PB9_GPIO_PuPd                        GPIO_NOPULL
#define MX_PB9_GPIO_Pin                         GPIO_PIN_9
#define MX_PB9_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PB8 */
#define MX_PB8_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB8_Pin                              PB8
#define MX_PB8_GPIOx                            GPIOB
#define MX_PB8_PinState                         GPIO_PIN_RESET
#define MX_PB8_GPIO_PuPd                        GPIO_NOPULL
#define MX_PB8_GPIO_Pin                         GPIO_PIN_8
#define MX_PB8_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PC14/OSC32_IN */
#define MX_PC14_OSC32_IN_GPIO_Speed             GPIO_SPEED_FREQ_LOW
#define MX_PC14_OSC32_IN_Pin                    PC14_OSC32_IN
#define MX_PC14_OSC32_IN_GPIOx                  GPIOC
#define MX_PC14_OSC32_IN_PinState               GPIO_PIN_RESET
#define MX_PC14_OSC32_IN_GPIO_PuPd              GPIO_NOPULL
#define MX_PC14_OSC32_IN_GPIO_Pin               GPIO_PIN_14
#define MX_PC14_OSC32_IN_GPIO_ModeDefaultOutputPP GPIO_MODE_OUTPUT_PP

/* Pin PG0 */
#define MX_PG0_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PG0_Pin                              PG0
#define MX_PG0_GPIOx                            GPIOG
#define MX_PG0_PinState                         GPIO_PIN_RESET
#define MX_PG0_GPIO_PuPd                        GPIO_NOPULL
#define MX_PG0_GPIO_Pin                         GPIO_PIN_0
#define MX_PG0_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PG2 */
#define MX_PG2_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PG2_Pin                              PG2
#define MX_PG2_GPIOx                            GPIOG
#define MX_PG2_PinState                         GPIO_PIN_RESET
#define MX_PG2_GPIO_PuPd                        GPIO_NOPULL
#define MX_PG2_GPIO_Pin                         GPIO_PIN_2
#define MX_PG2_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PG1 */
#define MX_PG1_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PG1_Pin                              PG1
#define MX_PG1_GPIOx                            GPIOG
#define MX_PG1_PinState                         GPIO_PIN_RESET
#define MX_PG1_GPIO_PuPd                        GPIO_NOPULL
#define MX_PG1_GPIO_Pin                         GPIO_PIN_1
#define MX_PG1_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PC0 */
#define MX_PC0_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PC0_Pin                              PC0
#define MX_PC0_GPIOx                            GPIOC
#define MX_PC0_PinState                         GPIO_PIN_RESET
#define MX_PC0_GPIO_PuPd                        GPIO_NOPULL
#define MX_PC0_GPIO_Pin                         GPIO_PIN_0
#define MX_PC0_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PG4 */
#define MX_PG4_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PG4_Pin                              PG4
#define MX_PG4_GPIOx                            GPIOG
#define MX_PG4_PinState                         GPIO_PIN_RESET
#define MX_PG4_GPIO_PuPd                        GPIO_NOPULL
#define MX_PG4_GPIO_Pin                         GPIO_PIN_4
#define MX_PG4_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PG3 */
#define MX_PG3_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PG3_Pin                              PG3
#define MX_PG3_GPIOx                            GPIOG
#define MX_PG3_PinState                         GPIO_PIN_RESET
#define MX_PG3_GPIO_PuPd                        GPIO_NOPULL
#define MX_PG3_GPIO_Pin                         GPIO_PIN_3
#define MX_PG3_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PC2 */
#define MX_PC2_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PC2_Pin                              PC2
#define MX_PC2_GPIOx                            GPIOC
#define MX_PC2_PinState                         GPIO_PIN_RESET
#define MX_PC2_GPIO_PuPd                        GPIO_NOPULL
#define MX_PC2_GPIO_Pin                         GPIO_PIN_2
#define MX_PC2_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PG6 */
#define MX_PG6_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PG6_Pin                              PG6
#define MX_PG6_GPIOx                            GPIOG
#define MX_PG6_PinState                         GPIO_PIN_RESET
#define MX_PG6_GPIO_PuPd                        GPIO_NOPULL
#define MX_PG6_GPIO_Pin                         GPIO_PIN_6
#define MX_PG6_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PC1 */
#define MX_PC1_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PC1_Pin                              PC1
#define MX_PC1_GPIOx                            GPIOC
#define MX_PC1_PinState                         GPIO_PIN_RESET
#define MX_PC1_GPIO_PuPd                        GPIO_NOPULL
#define MX_PC1_GPIO_Pin                         GPIO_PIN_1
#define MX_PC1_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PG5 */
#define MX_PG5_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PG5_Pin                              PG5
#define MX_PG5_GPIOx                            GPIOG
#define MX_PG5_PinState                         GPIO_PIN_RESET
#define MX_PG5_GPIO_PuPd                        GPIO_NOPULL
#define MX_PG5_GPIO_Pin                         GPIO_PIN_5
#define MX_PG5_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PC4 */
#define MX_PC4_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PC4_Pin                              PC4
#define MX_PC4_GPIOx                            GPIOC
#define MX_PC4_PinState                         GPIO_PIN_RESET
#define MX_PC4_GPIO_PuPd                        GPIO_NOPULL
#define MX_PC4_GPIO_Pin                         GPIO_PIN_4
#define MX_PC4_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PG8 */
#define MX_PG8_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PG8_Pin                              PG8
#define MX_PG8_GPIOx                            GPIOG
#define MX_PG8_PinState                         GPIO_PIN_RESET
#define MX_PG8_GPIO_PuPd                        GPIO_NOPULL
#define MX_PG8_GPIO_Pin                         GPIO_PIN_8
#define MX_PG8_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PC3 */
#define MX_PC3_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PC3_Pin                              PC3
#define MX_PC3_GPIOx                            GPIOC
#define MX_PC3_PinState                         GPIO_PIN_RESET
#define MX_PC3_GPIO_PuPd                        GPIO_NOPULL
#define MX_PC3_GPIO_Pin                         GPIO_PIN_3
#define MX_PC3_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PG7 */
#define MX_PG7_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PG7_Pin                              PG7
#define MX_PG7_GPIOx                            GPIOG
#define MX_PG7_PinState                         GPIO_PIN_RESET
#define MX_PG7_GPIO_PuPd                        GPIO_NOPULL
#define MX_PG7_GPIO_Pin                         GPIO_PIN_7
#define MX_PG7_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PC5 */
#define MX_PC5_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PC5_Pin                              PC5
#define MX_PC5_GPIOx                            GPIOC
#define MX_PC5_PinState                         GPIO_PIN_RESET
#define MX_PC5_GPIO_PuPd                        GPIO_NOPULL
#define MX_PC5_GPIO_Pin                         GPIO_PIN_5
#define MX_PC5_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PG9 */
#define MX_PG9_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PG9_Pin                              PG9
#define MX_PG9_GPIOx                            GPIOG
#define MX_PG9_PinState                         GPIO_PIN_RESET
#define MX_PG9_GPIO_PuPd                        GPIO_NOPULL
#define MX_PG9_GPIO_Pin                         GPIO_PIN_9
#define MX_PG9_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PC9 */
#define MX_PC9_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PC9_Pin                              PC9
#define MX_PC9_GPIOx                            GPIOC
#define MX_PC9_PinState                         GPIO_PIN_RESET
#define MX_PC9_GPIO_PuPd                        GPIO_NOPULL
#define MX_PC9_GPIO_Pin                         GPIO_PIN_9
#define MX_PC9_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PF10 */
#define MX_PF10_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PF10_Pin                             PF10
#define MX_PF10_GPIOx                           GPIOF
#define MX_PF10_PinState                        GPIO_PIN_RESET
#define MX_PF10_GPIO_PuPd                       GPIO_NOPULL
#define MX_PF10_GPIO_Pin                        GPIO_PIN_10
#define MX_PF10_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PD11 */
#define MX_PD11_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PD11_Pin                             PD11
#define MX_PD11_GPIOx                           GPIOD
#define MX_PD11_PinState                        GPIO_PIN_RESET
#define MX_PD11_GPIO_PuPd                       GPIO_NOPULL
#define MX_PD11_GPIO_Pin                        GPIO_PIN_11
#define MX_PD11_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PF12 */
#define MX_PF12_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PF12_Pin                             PF12
#define MX_PF12_GPIOx                           GPIOF
#define MX_PF12_PinState                        GPIO_PIN_RESET
#define MX_PF12_GPIO_PuPd                       GPIO_NOPULL
#define MX_PF12_GPIO_Pin                        GPIO_PIN_12
#define MX_PF12_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PB10 */
#define MX_PB10_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PB10_Pin                             PB10
#define MX_PB10_GPIOx                           GPIOB
#define MX_PB10_PinState                        GPIO_PIN_RESET
#define MX_PB10_GPIO_PuPd                       GPIO_NOPULL
#define MX_PB10_GPIO_Pin                        GPIO_PIN_10
#define MX_PB10_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PD10 */
#define MX_PD10_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PD10_Pin                             PD10
#define MX_PD10_GPIOx                           GPIOD
#define MX_PD10_PinState                        GPIO_PIN_RESET
#define MX_PD10_GPIO_PuPd                       GPIO_NOPULL
#define MX_PD10_GPIO_Pin                        GPIO_PIN_10
#define MX_PD10_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PB11 */
#define MX_PB11_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PB11_Pin                             PB11
#define MX_PB11_GPIOx                           GPIOB
#define MX_PB11_PinState                        GPIO_PIN_RESET
#define MX_PB11_GPIO_PuPd                       GPIO_NOPULL
#define MX_PB11_GPIO_Pin                        GPIO_PIN_11
#define MX_PB11_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PH3 */
#define MX_PH3_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PH3_Pin                              PH3
#define MX_PH3_GPIOx                            GPIOH
#define MX_PH3_PinState                         GPIO_PIN_RESET
#define MX_PH3_GPIO_PuPd                        GPIO_NOPULL
#define MX_PH3_GPIO_Pin                         GPIO_PIN_3
#define MX_PH3_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PH2 */
#define MX_PH2_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PH2_Pin                              PH2
#define MX_PH2_GPIOx                            GPIOH
#define MX_PH2_PinState                         GPIO_PIN_RESET
#define MX_PH2_GPIO_PuPd                        GPIO_NOPULL
#define MX_PH2_GPIO_Pin                         GPIO_PIN_2
#define MX_PH2_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PH5 */
#define MX_PH5_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PH5_Pin                              PH5
#define MX_PH5_GPIOx                            GPIOH
#define MX_PH5_PinState                         GPIO_PIN_RESET
#define MX_PH5_GPIO_PuPd                        GPIO_NOPULL
#define MX_PH5_GPIO_Pin                         GPIO_PIN_5
#define MX_PH5_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PF14 */
#define MX_PF14_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PF14_Pin                             PF14
#define MX_PF14_GPIOx                           GPIOF
#define MX_PF14_PinState                        GPIO_PIN_RESET
#define MX_PF14_GPIO_PuPd                       GPIO_NOPULL
#define MX_PF14_GPIO_Pin                        GPIO_PIN_14
#define MX_PF14_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PD1 */
#define MX_PD1_Pin                              PD1
#define MX_PD1_GPIOx                            GPIOD
#define MX_PD1_GPIO_PuPd                        GPIO_NOPULL
#define MX_PD1_GPIO_Pin                         GPIO_PIN_1
#define MX_PD1_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PH4 */
#define MX_PH4_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PH4_Pin                              PH4
#define MX_PH4_GPIOx                            GPIOH
#define MX_PH4_PinState                         GPIO_PIN_RESET
#define MX_PH4_GPIO_PuPd                        GPIO_NOPULL
#define MX_PH4_GPIO_Pin                         GPIO_PIN_4
#define MX_PH4_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PF13 */
#define MX_PF13_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PF13_Pin                             PF13
#define MX_PF13_GPIOx                           GPIOF
#define MX_PF13_PinState                        GPIO_PIN_RESET
#define MX_PF13_GPIO_PuPd                       GPIO_NOPULL
#define MX_PF13_GPIO_Pin                        GPIO_PIN_13
#define MX_PF13_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PD15 */
#define MX_PD15_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PD15_Pin                             PD15
#define MX_PD15_GPIOx                           GPIOD
#define MX_PD15_PinState                        GPIO_PIN_RESET
#define MX_PD15_GPIO_PuPd                       GPIO_NOPULL
#define MX_PD15_GPIO_Pin                        GPIO_PIN_15
#define MX_PD15_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PD0 */
#define MX_PD0_Pin                              PD0
#define MX_PD0_GPIOx                            GPIOD
#define MX_PD0_GPIO_PuPd                        GPIO_NOPULL
#define MX_PD0_GPIO_Pin                         GPIO_PIN_0
#define MX_PD0_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PD3 */
#define MX_PD3_Pin                              PD3
#define MX_PD3_GPIOx                            GPIOD
#define MX_PD3_GPIO_PuPd                        GPIO_NOPULL
#define MX_PD3_GPIO_Pin                         GPIO_PIN_3
#define MX_PD3_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PF15 */
#define MX_PF15_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PF15_Pin                             PF15
#define MX_PF15_GPIOx                           GPIOF
#define MX_PF15_PinState                        GPIO_PIN_RESET
#define MX_PF15_GPIO_PuPd                       GPIO_NOPULL
#define MX_PF15_GPIO_Pin                        GPIO_PIN_15
#define MX_PF15_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PH9 */
#define MX_PH9_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PH9_Pin                              PH9
#define MX_PH9_GPIOx                            GPIOH
#define MX_PH9_PinState                         GPIO_PIN_RESET
#define MX_PH9_GPIO_PuPd                        GPIO_NOPULL
#define MX_PH9_GPIO_Pin                         GPIO_PIN_9
#define MX_PH9_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PD5 */
#define MX_PD5_Pin                              PD5
#define MX_PD5_GPIOx                            GPIOD
#define MX_PD5_GPIO_PuPd                        GPIO_NOPULL
#define MX_PD5_GPIO_Pin                         GPIO_PIN_5
#define MX_PD5_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PH8 */
#define MX_PH8_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PH8_Pin                              PH8
#define MX_PH8_GPIOx                            GPIOH
#define MX_PH8_PinState                         GPIO_PIN_RESET
#define MX_PH8_GPIO_PuPd                        GPIO_NOPULL
#define MX_PH8_GPIO_Pin                         GPIO_PIN_8
#define MX_PH8_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PD4 */
#define MX_PD4_Pin                              PD4
#define MX_PD4_GPIOx                            GPIOD
#define MX_PD4_GPIO_PuPd                        GPIO_NOPULL
#define MX_PD4_GPIO_Pin                         GPIO_PIN_4
#define MX_PD4_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PD7 */
#define MX_PD7_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PD7_Pin                              PD7
#define MX_PD7_GPIOx                            GPIOD
#define MX_PD7_PinState                         GPIO_PIN_RESET
#define MX_PD7_GPIO_PuPd                        GPIO_NOPULL
#define MX_PD7_GPIO_Pin                         GPIO_PIN_7
#define MX_PD7_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PD6 */
#define MX_PD6_Pin                              PD6
#define MX_PD6_GPIOx                            GPIOD
#define MX_PD6_GPIO_PuPd                        GPIO_NOPULL
#define MX_PD6_GPIO_Pin                         GPIO_PIN_6
#define MX_PD6_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PD9 */
#define MX_PD9_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PD9_Pin                              PD9
#define MX_PD9_GPIOx                            GPIOD
#define MX_PD9_PinState                         GPIO_PIN_RESET
#define MX_PD9_GPIO_PuPd                        GPIO_NOPULL
#define MX_PD9_GPIO_Pin                         GPIO_PIN_9
#define MX_PD9_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PD8 */
#define MX_PD8_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PD8_Pin                              PD8
#define MX_PD8_GPIOx                            GPIOD
#define MX_PD8_PinState                         GPIO_PIN_RESET
#define MX_PD8_GPIO_PuPd                        GPIO_NOPULL
#define MX_PD8_GPIO_Pin                         GPIO_PIN_8
#define MX_PD8_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PB2/BOOT1 */
#define MX_PB2_BOOT1_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_PB2_BOOT1_Pin                        PB2_BOOT1
#define MX_PB2_BOOT1_GPIOx                      GPIOB
#define MX_PB2_BOOT1_PinState                   GPIO_PIN_RESET
#define MX_PB2_BOOT1_GPIO_PuPd                  GPIO_NOPULL
#define MX_PB2_BOOT1_GPIO_Pin                   GPIO_PIN_2
#define MX_PB2_BOOT1_GPIO_ModeDefaultOutputPP   GPIO_MODE_OUTPUT_PP

/* Pin PI1 */
#define MX_PI1_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PI1_Pin                              PI1
#define MX_PI1_GPIOx                            GPIOI
#define MX_PI1_PinState                         GPIO_PIN_RESET
#define MX_PI1_GPIO_PuPd                        GPIO_NOPULL
#define MX_PI1_GPIO_Pin                         GPIO_PIN_1
#define MX_PI1_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PE0 */
#define MX_PE0_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PE0_Pin                              PE0
#define MX_PE0_GPIOx                            GPIOE
#define MX_PE0_PinState                         GPIO_PIN_RESET
#define MX_PE0_GPIO_PuPd                        GPIO_NOPULL
#define MX_PE0_GPIO_Pin                         GPIO_PIN_0
#define MX_PE0_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PI4 */
#define MX_PI4_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PI4_Pin                              PI4
#define MX_PI4_GPIOx                            GPIOI
#define MX_PI4_PinState                         GPIO_PIN_RESET
#define MX_PI4_GPIO_PuPd                        GPIO_NOPULL
#define MX_PI4_GPIO_Pin                         GPIO_PIN_4
#define MX_PI4_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PI3 */
#define MX_PI3_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PI3_Pin                              PI3
#define MX_PI3_GPIOx                            GPIOI
#define MX_PI3_PinState                         GPIO_PIN_RESET
#define MX_PI3_GPIO_PuPd                        GPIO_NOPULL
#define MX_PI3_GPIO_Pin                         GPIO_PIN_3
#define MX_PI3_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PE2 */
#define MX_PE2_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PE2_Pin                              PE2
#define MX_PE2_GPIOx                            GPIOE
#define MX_PE2_PinState                         GPIO_PIN_RESET
#define MX_PE2_GPIO_PuPd                        GPIO_NOPULL
#define MX_PE2_GPIO_Pin                         GPIO_PIN_2
#define MX_PE2_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PE1 */
#define MX_PE1_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PE1_Pin                              PE1
#define MX_PE1_GPIOx                            GPIOE
#define MX_PE1_PinState                         GPIO_PIN_RESET
#define MX_PE1_GPIO_PuPd                        GPIO_NOPULL
#define MX_PE1_GPIO_Pin                         GPIO_PIN_1
#define MX_PE1_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PE4 */
#define MX_PE4_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PE4_Pin                              PE4
#define MX_PE4_GPIOx                            GPIOE
#define MX_PE4_PinState                         GPIO_PIN_RESET
#define MX_PE4_GPIO_PuPd                        GPIO_NOPULL
#define MX_PE4_GPIO_Pin                         GPIO_PIN_4
#define MX_PE4_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PI8 */
#define MX_PI8_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PI8_Pin                              PI8
#define MX_PI8_GPIOx                            GPIOI
#define MX_PI8_PinState                         GPIO_PIN_RESET
#define MX_PI8_GPIO_PuPd                        GPIO_NOPULL
#define MX_PI8_GPIO_Pin                         GPIO_PIN_8
#define MX_PI8_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PE3 */
#define MX_PE3_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PE3_Pin                              PE3
#define MX_PE3_GPIOx                            GPIOE
#define MX_PE3_PinState                         GPIO_PIN_RESET
#define MX_PE3_GPIO_PuPd                        GPIO_NOPULL
#define MX_PE3_GPIO_Pin                         GPIO_PIN_3
#define MX_PE3_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PI9 */
#define MX_PI9_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PI9_Pin                              PI9
#define MX_PI9_GPIOx                            GPIOI
#define MX_PI9_PinState                         GPIO_PIN_RESET
#define MX_PI9_GPIO_PuPd                        GPIO_NOPULL
#define MX_PI9_GPIO_Pin                         GPIO_PIN_9
#define MX_PI9_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PA3 */
#define MX_PA3_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PA3_Pin                              PA3
#define MX_PA3_GPIOx                            GPIOA
#define MX_PA3_PinState                         GPIO_PIN_RESET
#define MX_PA3_GPIO_PuPd                        GPIO_NOPULL
#define MX_PA3_GPIO_Pin                         GPIO_PIN_3
#define MX_PA3_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PE7 */
#define MX_PE7_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PE7_Pin                              PE7
#define MX_PE7_GPIOx                            GPIOE
#define MX_PE7_PinState                         GPIO_PIN_RESET
#define MX_PE7_GPIO_PuPd                        GPIO_NOPULL
#define MX_PE7_GPIO_Pin                         GPIO_PIN_7
#define MX_PE7_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PA8 */
#define MX_PA8_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PA8_Pin                              PA8
#define MX_PA8_GPIOx                            GPIOA
#define MX_PA8_PinState                         GPIO_PIN_RESET
#define MX_PA8_GPIO_PuPd                        GPIO_NOPULL
#define MX_PA8_GPIO_Pin                         GPIO_PIN_8
#define MX_PA8_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PA7 */
#define MX_PA7_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PA7_Pin                              PA7
#define MX_PA7_GPIOx                            GPIOA
#define MX_PA7_PinState                         GPIO_PIN_RESET
#define MX_PA7_GPIO_PuPd                        GPIO_NOPULL
#define MX_PA7_GPIO_Pin                         GPIO_PIN_7
#define MX_PA7_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PC13 */
#define MX_PC13_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PC13_Pin                             PC13
#define MX_PC13_GPIOx                           GPIOC
#define MX_PC13_PinState                        GPIO_PIN_RESET
#define MX_PC13_GPIO_PuPd                       GPIO_NOPULL
#define MX_PC13_GPIO_Pin                        GPIO_PIN_13
#define MX_PC13_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PA15 */
#define MX_PA15_Pin                             PA15
#define MX_PA15_GPIOx                           GPIOA
#define MX_PA15_GPIO_PuPd                       GPIO_NOPULL
#define MX_PA15_GPIO_Pin                        GPIO_PIN_15
#define MX_PA15_GPIO_Mode                       GPIO_MODE_INPUT

/* Pin PC15/OSC32_OUT */
#define MX_PC15_OSC32_OUT_GPIO_Speed            GPIO_SPEED_FREQ_LOW
#define MX_PC15_OSC32_OUT_Pin                   PC15_OSC32_OUT
#define MX_PC15_OSC32_OUT_GPIOx                 GPIOC
#define MX_PC15_OSC32_OUT_PinState              GPIO_PIN_RESET
#define MX_PC15_OSC32_OUT_GPIO_PuPd             GPIO_NOPULL
#define MX_PC15_OSC32_OUT_GPIO_Pin              GPIO_PIN_15
#define MX_PC15_OSC32_OUT_GPIO_ModeDefaultOutputPP GPIO_MODE_OUTPUT_PP

/* Pin PG11 */
#define MX_PG11_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PG11_Pin                             PG11
#define MX_PG11_GPIOx                           GPIOG
#define MX_PG11_PinState                        GPIO_PIN_RESET
#define MX_PG11_GPIO_PuPd                       GPIO_NOPULL
#define MX_PG11_GPIO_Pin                        GPIO_PIN_11
#define MX_PG11_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PG10 */
#define MX_PG10_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PG10_Pin                             PG10
#define MX_PG10_GPIOx                           GPIOG
#define MX_PG10_PinState                        GPIO_PIN_RESET
#define MX_PG10_GPIO_PuPd                       GPIO_NOPULL
#define MX_PG10_GPIO_Pin                        GPIO_PIN_10
#define MX_PG10_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PI11 */
#define MX_PI11_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PI11_Pin                             PI11
#define MX_PI11_GPIOx                           GPIOI
#define MX_PI11_PinState                        GPIO_PIN_RESET
#define MX_PI11_GPIO_PuPd                       GPIO_NOPULL
#define MX_PI11_GPIO_Pin                        GPIO_PIN_11
#define MX_PI11_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PF3 */
#define MX_PF3_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PF3_Pin                              PF3
#define MX_PF3_GPIOx                            GPIOF
#define MX_PF3_PinState                         GPIO_PIN_RESET
#define MX_PF3_GPIO_PuPd                        GPIO_NOPULL
#define MX_PF3_GPIO_Pin                         GPIO_PIN_3
#define MX_PF3_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PE15 */
#define MX_PE15_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PE15_Pin                             PE15
#define MX_PE15_GPIOx                           GPIOE
#define MX_PE15_PinState                        GPIO_PIN_RESET
#define MX_PE15_GPIO_PuPd                       GPIO_NOPULL
#define MX_PE15_GPIO_Pin                        GPIO_PIN_15
#define MX_PE15_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PI10 */
#define MX_PI10_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PI10_Pin                             PI10
#define MX_PI10_GPIOx                           GPIOI
#define MX_PI10_PinState                        GPIO_PIN_RESET
#define MX_PI10_GPIO_PuPd                       GPIO_NOPULL
#define MX_PI10_GPIO_Pin                        GPIO_PIN_10
#define MX_PI10_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PF2 */
#define MX_PF2_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PF2_Pin                              PF2
#define MX_PF2_GPIOx                            GPIOF
#define MX_PF2_PinState                         GPIO_PIN_RESET
#define MX_PF2_GPIO_PuPd                        GPIO_NOPULL
#define MX_PF2_GPIO_Pin                         GPIO_PIN_2
#define MX_PF2_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PE14 */
#define MX_PE14_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PE14_Pin                             PE14
#define MX_PE14_GPIOx                           GPIOE
#define MX_PE14_PinState                        GPIO_PIN_RESET
#define MX_PE14_GPIO_PuPd                       GPIO_NOPULL
#define MX_PE14_GPIO_Pin                        GPIO_PIN_14
#define MX_PE14_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PF5 */
#define MX_PF5_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PF5_Pin                              PF5
#define MX_PF5_GPIOx                            GPIOF
#define MX_PF5_PinState                         GPIO_PIN_RESET
#define MX_PF5_GPIO_PuPd                        GPIO_NOPULL
#define MX_PF5_GPIO_Pin                         GPIO_PIN_5
#define MX_PF5_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PB1 */
#define MX_PB1_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB1_Pin                              PB1
#define MX_PB1_GPIOx                            GPIOB
#define MX_PB1_PinState                         GPIO_PIN_RESET
#define MX_PB1_GPIO_PuPd                        GPIO_NOPULL
#define MX_PB1_GPIO_Pin                         GPIO_PIN_1
#define MX_PB1_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PG15 */
#define MX_PG15_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PG15_Pin                             PG15
#define MX_PG15_GPIOx                           GPIOG
#define MX_PG15_PinState                        GPIO_PIN_RESET
#define MX_PG15_GPIO_PuPd                       GPIO_NOPULL
#define MX_PG15_GPIO_Pin                        GPIO_PIN_15
#define MX_PG15_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PF4 */
#define MX_PF4_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PF4_Pin                              PF4
#define MX_PF4_GPIOx                            GPIOF
#define MX_PF4_PinState                         GPIO_PIN_RESET
#define MX_PF4_GPIO_PuPd                        GPIO_NOPULL
#define MX_PF4_GPIO_Pin                         GPIO_PIN_4
#define MX_PF4_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PB0 */
#define MX_PB0_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB0_Pin                              PB0
#define MX_PB0_GPIOx                            GPIOB
#define MX_PB0_PinState                         GPIO_PIN_RESET
#define MX_PB0_GPIO_PuPd                        GPIO_NOPULL
#define MX_PB0_GPIO_Pin                         GPIO_PIN_0
#define MX_PB0_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

#endif  /* __MX_DEVICE_H */

